aqi/aqi/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    # path('prediction/', include('prediction.urls')),
    path('download/', include('download.urls')),
    path('history/', include('history.urls')),
    path('login/', include('login.urls')),
    path('aqi_prediction/', include('aqi_prediction.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aqi/download/urls.py
from django.urls import path
from . import views

app_name = 'download'

urlpatterns = [
    path('', views.download_page, name='download_page'),  # For the download button
    path('download_csv/', views.download_csv, name='download_csv'),  # For the actual download
]

aqi/download/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
import os
from django.conf import settings
from django.utils.encoding import smart_str

def download_page(request):
     return render(request, 'download//download.html')

def download_csv(request):
    file_path = os.path.join(settings.MEDIA_ROOT, 'filtered_data.csv')
    
    if os.path.exists(file_path):
        with open(file_path, 'rb') as f:
            response = HttpResponse(f.read(), content_type='text/csv')
            response['Content-Disposition'] = 'attachment; filename=%s' % smart_str('filtered_data.csv')
            return response
    else:
        raise Http404("File not found")

aqi/download/templates/download/download.html
{% extends "layout.html" %}
{% block title %}
<title>Download Data</title>
{% endblock %}{% block content %}
<body class="bg-teal-100">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <!-- Main content -->
    <div class="container mx-auto my-8">
        <div class="mt-8 p-6 bg-white rounded-lg shadow-lg">
            <h2 class="text-2xl font-bold text-gray-800 flex items-center">
                <i class="fas fa-download mr-2 text-blue-500"></i> Download AQI Data
            </h2>
            <p class="text-lg text-gray-600 mt-4">Download the latest air quality index data in CSV format.</p>

            <div class="mt-6">
                <form action="{% url 'download:download_csv' %}" method="get">
                    <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                        Download CSV
                    </button>
                </form>
            </div>
        </div>
    </div>
</body>
{% endblock %}